# https://golangci-lint.run/usage/linters/
run:
  go: "1.22"
  timeout: 3m
  allow-parallel-runners: true

output:
  formats: colored-line-number

linters:
  disable-all: true
  enable:
    - gosimple # Suggest code simplifications
    - govet # Reports suspicious constructs
    - ineffassign # Detects unused variable assignments
    - staticcheck # go vet on steroids
    - unused # Detect unused constants, variables, functions, and types
    - gocyclo # Detect cyclomatic complexity
    - gofumpt
    - goimports
    - misspell # Fix spelling errors
    - bodyclose # Check whether HTTP response bodies are closed

linters-settings:
  gofumpt:
    module-path: "dojo-api"

issues:
  exclude-use-default: false
  exclude-dirs:
    - dojo-api/db
  exclude-rules:
    - path: ".*"
      linters:
        - typecheck
