# Dockerfile.prisma

FROM golang:1.22

# Set the working directory inside the container
WORKDIR /app

# Copy Go modules manifest
COPY go.mod go.sum ./

# Copy the Prisma schema file
COPY schema.prisma ./

# prefetch the binaries, so that they will be cached and not downloaded on each change
RUN go run github.com/steebchen/prisma-client-go prefetch

CMD go run github.com/steebchen/prisma-client-go generate && \
    go run github.com/steebchen/prisma-client-go db push
