@url = http://localhost:3000

###
POST {{url}}/api/v1/worker/login/auth
Content-Type: application/json

{
    "walletAddress": "0x4a13147277b4e2E7Fe4Eaf41d72Ffcf7EB2F55D9",
    "chainId": "1",
    "signature": "0xf6c8d429a1e9aacb4debe62d08b6c1ca4ed8adbd59addbf066e0d77b110d1d8812720e63d24d19d39a731ffad83c2118176029d4e5da33a28d4a3c6ad11117b01c",
    "message": "localhost:3000 wants you to sign in with your Ethereum account:\n0x4a13147277b4e2E7Fe4Eaf41d72Ffcf7EB2F55D9\n\nSign in with Ethereum to tensorplex\n\nURI: http://localhost:3000\nVersion: 1\nChain ID: 1\nNonce: 2lfsl2N8dLFsAU9Tk\nIssued At: 2024-05-02T05:43:02.368Z",
    "timestamp": "1714640093"
}

###
POST {{url}}/api/v1/miner/login/auth
Content-Type: application/json

{
   "hotkey" : "1221212356jkhsesdsldjklsd87273208090",
   "coldkey" : "78980090870392jzdskjdsd7"
}

POST {{url}}/api/v1/tasks
Content-Type: application/json

{
  "title": "Task Title",
  "body": "Detailed task description",
  "expireAt": "2024-12-03 15:04:05",
  "taskData": [
    {
        "prompt": "Write me a program that visualized our solar system, you may use python, javascript or pure HTML.",
        "responses": [
            {
                "model": "openai/gpt-4-turbo",
                "completion": {
                        "code": "print('\''Hello World'\'')",
                        "language": "python",
                        "installation_commands": "null",
                        "additional_notes": "The code uses built-in libraries so no additional commands are required."
                    }
            },
            {
                "model": "phind/phind-codellama-34b",
                "completion": {
                    "code": "import matplotlib.pyplot as plt\r\n\r\n# Define the distances from the Sun for each planet in millions of km\r\ndistance_from_sun = [57.9, 108.2, 149.6, 227.9, 778.6, 1433.5]\r\n\r\n# Define the planet names\r\nplanet_names = ['\''Mercury'\'', '\''Venus'\'', '\''Earth'\'', '\''Mars'\'', '\''Jupiter'\'', '\''Saturn'\'']\r\n\r\n# Plot the orbits\r\nfig, ax = plt.subplots()\r\nfor i in range(len(planet_names)):\r\n    ax.plot(0, 0, '\''o'\'', label=planet_names[i])\r\n    ax.plot([0, distance_from_sun[i]], [0, 0], '\''--'\'')\r\n\r\nax.legend()\r\nplt.show()\r\n",
                    "language": "python",
                    "installation_commands": "pip install matplotlib",
                    "additional_notes": "The code uses the matplotlib library to create the visualization of the solar system. You can install it using the command '\''pip install matplotlib'\''."
                    }
            }
        ],
        "task": "CODE_GENERATION",
        "criteria": [
            {
                "type": "ranking",
                "options": [
                "Code 1",
                "Code 2"
                ]
            },
            {
                "type": "multi-select",
                "options": [
                   "The code is well-written and clear.",
                   "The code does not have any malicious intent.",
                   "The code correctly accepts user input."
               ]
           },
           {
                "type": "score",
                "min": 1.0,
                "max": 10.0
           }
        ]
    },
  ],
  "maxResults": 10,
  "totalRewards": 100.3,
}

###
PUT {{url}}/api/v1/partner/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkb2pvLWFwaSIsInN1YiI6IjB4MDVhYTFhYWI1ZEQ4ZTFERjMwM0NBMUM5Y2I2RTNGNWQ3NDViODM4OSIsImV4cCI6MTcxNDYyOTE5Nn0.UOOs9T-Xcglyi4urXxITMhw69ScPOPcHfzxQZlXXGy0

{
   "miner_subscription_key" : "12356",
   "name" : "some_guy",
   "new_miner_subscription_key": "7890"
}


PUT {{url}}/api/v1/worker/partner/disable
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkb2pvLWFwaSIsInN1YiI6IjB4MDVhYTFhYWI1ZEQ4ZTFERjMwM0NBMUM5Y2I2RTNGNWQ3NDViODM4OSIsImV4cCI6MTcxNDYyOTE5Nn0.UOOs9T-Xcglyi4urXxITMhw69ScPOPcHfzxQZlXXGy0

{
    "miner_subscription_key" : "",
    "to_disable": true
}


PUT {{url}}/api/v1/miner/partner/disable
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkb2pvLWFwaSIsInN1YiI6IjB4MDVhYTFhYWI1ZEQ4ZTFERjMwM0NBMUM5Y2I2RTNGNWQ3NDViODM4OSIsImV4cCI6MTcxNDYyOTE5Nn0.UOOs9T-Xcglyi4urXxITMhw69ScPOPcHfzxQZlXXGy0

{
    "worker_id" : "",
    "to_disable": true
}




###
GET {{url}}/api/v1/auth/0x4a13147277b4e2E7Fe4Eaf41d72Ffcf7EB2F55D9
