name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.0
        env:
          POSTGRES_DB: subnet_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1

      - name: Wait for Postgres to be available
        run: |
          for i in `seq 1 30`; do
            nc -z localhost 5432 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for Postgres && exit 1

      - name: Tidy Go Modules
        run: go mod tidy

      - name: Generate Prisma Client
        run: go run github.com/steebchen/prisma-client-go generate

      - name: Push Prisma DB
        run: go run github.com/steebchen/prisma-client-go db push

      - name: Run golangci-lint
        run: golangci-lint run --fast --timeout 10m
